services:
  backend:
    build:
      context: ./backend
    container_name: weather-backend
    environment:
      NODE_ENV: production
      PORT: 3001
      GEOCODATA_API_URL: https://geocoding-api.open-meteo.com
      OPEN_METEO_HISTORICAL_API_URL: https://archive-api.open-meteo.com
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3001:3001'
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_WEATHER_BE_BASE_URL: http://localhost:3001
    container_name: weather-frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: weather-redis
